version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskapp
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      retries: 5
      start_period: 20s
    networks:
      - app_network

  backend:
    build:
      context: ./server   # Path to your Node.js backend project directory
      dockerfile: Dockerfile
    container_name: node_backend
    restart: always
    ports:
      - "8181:8181"  # Maps host port 8181 to container's port 8181
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: taskapp
      DB_PORT: 3307
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  frontend:
    build:
      context: ./client  # Path to your Next.js frontend project directory
      dockerfile: Dockerfile
    container_name: next_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
