version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskapp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./server   # Path to your Node.js backend project directory
      dockerfile: Dockerfile
    container_name: node_backend
    restart: always
    ports:
      - "3001:3000"  # Maps host port 3001 to container's port 3000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: taskapp
    depends_on:
      - db

  frontend:
    build:
      context: ./client  # Path to your Next.js frontend project directory
      dockerfile: Dockerfile
    container_name: next_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
